name: Deploy Next to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sadid369/nextcicd:latest
          no-cache: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull sadid369/nextcicd:latest || true
            sudo docker stop nextcicd || true
            sudo docker rm nextcicd || true
            sudo docker rmi sadid369/nextcicd:latest || true  # Remove old image
            sudo docker pull sadid369/nextcicd:latest           # Fresh pull
            sudo docker run -d --name nextcicd -p 3000:3000 sadid369/nextcicd:latest
            sudo systemctl reload nginx
